---
driver:
  name: vagrant
  box: chef/centos-6.5
  network:
    - ["forwarded_port", {guest: 8080, host: 9090, auto_correct: true}]
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.0
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[meanapp-pipeline::default]
    attributes:
      chef-zero:
        start: true
      resolver:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4