name             'meanapp-pipeline'
maintainer       'Dylan Johnson'
maintainer_email 'therealdylanjohnson@gmail.com'
license          ''
description      'Installs/Configures meanapp-pipeline'
long_description 'Installs/Configures meanapp-pipeline'
version          '0.1.1'

depends 'apt', '>= 0.0.0'
depends 'yum', '>= 0.0.0'
depends 'git', '>= 0.0.0'
depends 'java', '>= 0.0.0'
depends 'jenkins', '>= 0.0.0'
depends 'chef-zero', '>= 0.0.0'
depends 'emacs', '>= 0.0.0'
depends 'sudo', '>= 0.0.0'
depends 'chef-dk', '>= 0.0.0'
depends 'resolver', '>= 0.0.0'
depends 'pipeline', '2.1.0'